
-- Inserts para testes da classe User, e para a classe Address.

INSERT INTO USER ( NAME , CPF,  DATE_OF_BIRTH , EMAIL ) VALUES ('Cauê Benedito Araújo', '80563885831', '1989-07-15', 'caue.araujo@gmail.com');
INSERT INTO USER ( NAME , CPF,  DATE_OF_BIRTH , EMAIL ) VALUES ('Severino Calebe Nogueira', '37868581875', '1982-06-15', 'severino.nogueira@gmail.com');
INSERT INTO USER ( NAME , CPF,  DATE_OF_BIRTH , EMAIL ) VALUES ('Nicole Aline Sophia Galvão', '57029218876', '1980-06-21', 'nicole.galvao@gmail.com');
INSERT INTO USER ( NAME , CPF,  DATE_OF_BIRTH , EMAIL ) VALUES ('Ayla Laura Campos', '13225604801', '1976-03-17', 'ayla.campos@gmail.com');
INSERT INTO USER ( NAME , CPF,  DATE_OF_BIRTH , EMAIL ) VALUES ('Theo Otávio Figueiredo', '61954077807', '1971-11-20', 'theo.figueiredo@gmail.com');


INSERT INTO ADDRESS (CITY, COMPLEMENT, DISTRICT, NUMBER, PUBLIC_PLACE, UF, ZIP_CODE, USER_ID) VALUES ('CUBATAO', 'CASA', 'VILA NATAL', '238', 'RUA VINTE E CINCO DE DEZEMBRO', 'SP', '11538000',2);
INSERT INTO ADDRESS (CITY, COMPLEMENT, DISTRICT, NUMBER, PUBLIC_PLACE, UF, ZIP_CODE, USER_ID) VALUES ('Guarulhos', 'CASA', 'Jardim Paraíso', '512', 'Avenida Silvestre Pires de Freitas', 'SP', '07144000',1 );
INSERT INTO ADDRESS (CITY, COMPLEMENT, DISTRICT, NUMBER, PUBLIC_PLACE, UF, ZIP_CODE, USER_ID) VALUES ('Natal', 'CASA', 'Pajuçara', '197', 'Rua Lagoa Real', 'RN', '59131800', 1);
INSERT INTO ADDRESS (CITY, COMPLEMENT, DISTRICT, NUMBER, PUBLIC_PLACE, UF, ZIP_CODE, USER_ID) VALUES ('São Lourenço da Mata', 'CASA', 'Penedo', '476', 'Rua Tomaz Antônio Gonzaga', 'PE', '54710340', 3);
INSERT INTO ADDRESS (CITY, COMPLEMENT, DISTRICT, NUMBER, PUBLIC_PLACE, UF, ZIP_CODE, USER_ID) VALUES ('Belém', 'CASA', 'Penedo', '160', 'Vila Nilza', 'PA', '66070035', 5);
INSERT INTO ADDRESS (CITY, COMPLEMENT, DISTRICT, NUMBER, PUBLIC_PLACE, UF, ZIP_CODE, USER_ID) VALUES ('Manaus', 'CASA', 'Cidade Nova', '990', 'Rua Tulipa', 'AM', '69096650', 4);
INSERT INTO ADDRESS (CITY, COMPLEMENT, DISTRICT, NUMBER, PUBLIC_PLACE, UF, ZIP_CODE, USER_ID) VALUES ('Mauá', 'CASA', 'Vila Nova Mauá', '183', 'Rua Jarda Ferreira dos Santos', 'SP', '09390800', 3);
INSERT INTO ADDRESS (CITY, COMPLEMENT, DISTRICT, NUMBER, PUBLIC_PLACE, UF, ZIP_CODE, USER_ID) VALUES ('Feira de Santana', 'CASA', 'Serraria Brasil', '482', 'Avenida Senhor dos Passos', 'BA', '44003144', 2);
INSERT INTO ADDRESS (CITY, COMPLEMENT, DISTRICT, NUMBER, PUBLIC_PLACE, UF, ZIP_CODE, USER_ID) VALUES ('Maceió', 'CASA', 'Jacintinho', '983', 'Avenida Juca Sampaio', 'AL', '57040600',2);
INSERT INTO ADDRESS (CITY, COMPLEMENT, DISTRICT, NUMBER, PUBLIC_PLACE, UF, ZIP_CODE, USER_ID) VALUES ('Mossoró', 'CASA', 'Doze Anos', '517', 'Rua Pedro Velho', 'RN', '59603410', 3);